# Generated by Django 5.1.5 on 2025-02-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personal_email',
            new_name='email',
        ),
    ]
