# Generated by Django 5.1.5 on 2025-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_categories_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out'), ('Discontinued', 'Discontinued')], default='Available', max_length=20),
        ),
    ]
